### ISSUE TITLE
Cannot find importmagic and epc

### ISSUE THREAD

**Issue by ztlevi** [anachronic/importmagic.el#10] opened 2018-01-08 05:35 UTC
I'm using pip3 to install these dependencies. I tried pip as well but no luck get this working.

After installing the dependencies. I get:
```
Requirement already satisfied: importmagic in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: epc in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: setuptools>=0.6b1 in /usr/local/lib/python3.6/site-pack
ages (from importmagic)                                                              
Requirement already satisfied: sexpdata>=0.0.3 in /usr/local/lib/python3.6/site-packag
es (from epc)                                                                        
```

And I get the error message when opening a python file.
```
Importmagic and/or epc not found. importmagic.el will not be working.
```

Do I have to configure this just like what this sublime plugin did [here](https://github.com/alecthomas/SublimePythonImportMagic#configuration)?

**Comment by anachronic** [comment] 2018-01-28 17:44
Hi, and sorry for the late response.

You don't have to configure anything other than just installing the dependencies.

Would you care to explain a little more about your environment? Like saying if you are using any sort of virtual environments and python versions? I can't really reproduce this.

**Comment by ztlevi** [comment] 2018-01-28 19:06
Sure. I'm using Spacemacs so most of the python thing is configured as default.

You can find the importmagic setting from Spacemacs [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/python/packages.el#L151). 

And the python interpreter is ipython.
```
python-shell-interpreter is a variable defined in ‘python.el’.
Its value is "ipython"
Original value was "python"
```

```shell
➜ ipython --version
6.2.1
➜ which -a ipython
/usr/local/bin/ipython
/usr/local/anaconda3/bin/ipython
```
So I believe it's a python3 version ipython.
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3eb6ae2)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy

**Comment by anachronic** [comment] 2018-04-27 03:41
It seems a little weird to me, and I don't really think #12 will fix it, as importmagic uses hardcoded python for now.

The only thing I can think is causing this is you're maybe inside some virtual environment that doesn't have importmagic or epc, while your global environment does have them.

**Comment by ztlevi** [comment] 2018-04-27 19:05
I figure out I have to install the packages using `pip2` because most machines use `python2` as the symbolic link of `python`. I not sure how this will change after we move to the `python-shell-interpreter` instead of hardcoded `python`. This should be fixed or at least mentioned in the README otherwise `python3` users will not get `importmagic` working.

Also, It doesn't matter if I am using a virtual environment or not. At least in my case, I can invoke `importmagic` as long as I installed the dependencies via `pip2`.

**Comment by anachronic** [comment] 2018-04-27 20:25
Alright, I'll mention it in the readme when setting the `python-shell-interpreter` command is available, but for now I guess we're stuck with `python`.

I'm gonna go ahead and close this. If you encounter any more issues please open them.

**Closed as completed by anachronic** 2018-04-27 20:25 UTC
Labels: needs feedback

**Comment by Victornovikov** [comment] 2021-01-19 05:19
looks like I am having the same issue.
python-shell-interpreter has hardcoded `python` my Ubuntu 20.04 only has python3 and pip3.

**Comment by fireinice** [comment] 2022-07-17 04:11
> looks like I am having the same issue. python-shell-interpreter has hardcoded `python` my Ubuntu 20.04 only has python3 and pip3.

I encounter the same problem recently, for others may concern, it seems related to the conda environment, you can check `which pip` and `which python` first to make sure both in the same environment
